name: geocomp
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - requests
  - tqdm
  - matplotlib
  - scipy
  - numpy
  - jupyter
  - jupyterlab
  - ipykernel
  - ipywidgets
  - ipyparallel
  - scikit-image
  - scikit-learn
  - pillow
  - h5py
  - pandas
  - seaborn
  - pint
  - cartopy
  - geopandas
  - xarray
  - descartes            # Geology
  - mapclassify          # Geology
  - verde                # Geophysics
  - umap-learn           # ML
  - hdbscan              # ML
  - fastai::fastai       # ML
  - pytorch::pytorch     # ML
  - pytorch::torchvision # ML
  - pytorch::cpuonly     # ML
  - skorch               # ML
  - pip:
    - bruges
    - welly
    - wellpathpy
    - segyio
    - dlisio
    - mplstereonet         # Geology
    - pandas-profiling[notebook]     # Geology
    - pyrolite             # Geology
    - segysak              # Geophysics
    - pylops               # Geophysics
    - torchlayers          # ML
